/* tslint:disable */
/* eslint-disable */
/**
 * Mnestix AAS Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { CreateAasResponse, ProblemDetails } from '../models/index';

export interface AasCreatorCreateAasRequest {
    assetIdShort: string;
}

/**
 *
 */
export class AasCreatorApi extends runtime.BaseAPI {
    /**
     * Creates a new AAS for a given assetIdShort. Response contains id of the newly generated AAS Base64UrlEncoded.
     */
    async aasCreatorCreateAasRaw(
        requestParameters: AasCreatorCreateAasRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<CreateAasResponse>> {
        if (requestParameters['assetIdShort'] == null) {
            throw new runtime.RequiredError(
                'assetIdShort',
                'Required parameter "assetIdShort" was null or undefined when calling aasCreatorCreateAas().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/api/AasCreator/{assetIdShort}`.replace(
                    `{${'assetIdShort'}}`,
                    encodeURIComponent(String(requestParameters['assetIdShort'])),
                ),
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Creates a new AAS for a given assetIdShort. Response contains id of the newly generated AAS Base64UrlEncoded.
     */
    async aasCreatorCreateAas(
        requestParameters: AasCreatorCreateAasRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<CreateAasResponse> {
        const response = await this.aasCreatorCreateAasRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
