/* tslint:disable */
/* eslint-disable */
/**
 * Mnestix AAS Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { Aas, ProblemDetails } from '../models/index';

export interface AasRelationshipGetDerivedFromRequest {
    aasId?: string;
}

/**
 *
 */
export class AasRelationshipApi extends runtime.BaseAPI {
    /**
     * Returns all asset administration shells that have a direct derivedFrom dependency on the given asset administration shell
     */
    async aasRelationshipGetDerivedFromRaw(
        requestParameters: AasRelationshipGetDerivedFromRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<Aas>>> {
        const queryParameters: any = {};

        if (requestParameters['aasId'] != null) {
            queryParameters['aasId'] = requestParameters['aasId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/api/AasRelationship/GetDerivedFrom`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns all asset administration shells that have a direct derivedFrom dependency on the given asset administration shell
     */
    async aasRelationshipGetDerivedFrom(
        requestParameters: AasRelationshipGetDerivedFromRequest = {},
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<Aas>> {
        const response = await this.aasRelationshipGetDerivedFromRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
