/* tslint:disable */
/* eslint-disable */
/**
 * Mnestix AAS Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ProblemDetails } from '../models/index';

export interface ConfigurationPatchIdConfigurationRequest {
    idShortPath?: string;
    value?: string;
}

/**
 *
 */
export class ConfigurationApi extends runtime.BaseAPI {
    /**
     * Retrieves the current ID generation configuration settings.
     */
    async configurationGetIdConfigurationRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/api/Configuration`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieves the current ID generation configuration settings.
     */
    async configurationGetIdConfiguration(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.configurationGetIdConfigurationRaw(initOverrides);
    }

    /**
     * Applies a partial update to a specific ID generation configuration value.
     */
    async configurationPatchIdConfigurationRaw(
        requestParameters: ConfigurationPatchIdConfigurationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['idShortPath'] != null) {
            queryParameters['idShortPath'] = requestParameters['idShortPath'];
        }

        if (requestParameters['value'] != null) {
            queryParameters['value'] = requestParameters['value'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/api/Configuration`,
                method: 'PATCH',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Applies a partial update to a specific ID generation configuration value.
     */
    async configurationPatchIdConfiguration(
        requestParameters: ConfigurationPatchIdConfigurationRequest = {},
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.configurationPatchIdConfigurationRaw(requestParameters, initOverrides);
    }
}
