/* tslint:disable */
/* eslint-disable */
/**
 * Mnestix AAS Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { AddDataToAasRequest, AddDataToAasResponse, ProblemDetails } from '../models/index';

export interface DataIngestAddDataToAasRequest {
    base64EncodedAasId: string;
    addDataToAasRequest: AddDataToAasRequest;
}

/**
 *
 */
export class DataIngestApi extends runtime.BaseAPI {
    /**
     * Takes the submodel templates with given customTemplateIds and maps the data from the given data json into them. After that, it will store the submodels into the shell with given aasId with its submodel short id.
     */
    async dataIngestAddDataToAasRaw(
        requestParameters: DataIngestAddDataToAasRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<AddDataToAasResponse>> {
        if (requestParameters['base64EncodedAasId'] == null) {
            throw new runtime.RequiredError(
                'base64EncodedAasId',
                'Required parameter "base64EncodedAasId" was null or undefined when calling dataIngestAddDataToAas().',
            );
        }

        if (requestParameters['addDataToAasRequest'] == null) {
            throw new runtime.RequiredError(
                'addDataToAasRequest',
                'Required parameter "addDataToAasRequest" was null or undefined when calling dataIngestAddDataToAas().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request(
            {
                path: `/api/DataIngest/{base64EncodedAasId}`.replace(
                    `{${'base64EncodedAasId'}}`,
                    encodeURIComponent(String(requestParameters['base64EncodedAasId'])),
                ),
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters['addDataToAasRequest'],
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Takes the submodel templates with given customTemplateIds and maps the data from the given data json into them. After that, it will store the submodels into the shell with given aasId with its submodel short id.
     */
    async dataIngestAddDataToAas(
        requestParameters: DataIngestAddDataToAasRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<AddDataToAasResponse> {
        const response = await this.dataIngestAddDataToAasRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
