/* tslint:disable */
/* eslint-disable */
/**
 * Mnestix AAS Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface DefaultTemplatesAddDefaultSubmodelTemplateRequest {
    body: any | null;
}

/**
 *
 */
export class DefaultTemplatesApi extends runtime.BaseAPI {
    /**
     * Creates a new custom template in the custom templates AAS. Submodel Id needs to be unique and present in JSON body.
     */
    async defaultTemplatesAddDefaultSubmodelTemplateRaw(
        requestParameters: DefaultTemplatesAddDefaultSubmodelTemplateRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling defaultTemplatesAddDefaultSubmodelTemplate().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request(
            {
                path: `/api/DefaultTemplates`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters['body'] as any,
            },
            initOverrides,
        );

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Creates a new custom template in the custom templates AAS. Submodel Id needs to be unique and present in JSON body.
     */
    async defaultTemplatesAddDefaultSubmodelTemplate(
        requestParameters: DefaultTemplatesAddDefaultSubmodelTemplateRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Blob> {
        const response = await this.defaultTemplatesAddDefaultSubmodelTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
