/* tslint:disable */
/* eslint-disable */
/**
 * Mnestix AAS Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { AasIds } from '../models/index';

export interface IdGeneratorGenerateIdsRequest {
    assetIdShort: string;
}

export interface IdGeneratorGenerateSubmodelIdsRequest {
    count: number;
}

/**
 *
 */
export class IdGeneratorApi extends runtime.BaseAPI {
    /**
     * Generates a set of ids which is used to create a new AAS. Response contains: - AasId - AasIdShort - AssetId - AssetIdShort
     */
    async idGeneratorGenerateIdsRaw(
        requestParameters: IdGeneratorGenerateIdsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<AasIds>> {
        if (requestParameters['assetIdShort'] == null) {
            throw new runtime.RequiredError(
                'assetIdShort',
                'Required parameter "assetIdShort" was null or undefined when calling idGeneratorGenerateIds().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/api/IdGenerator/aasIds/{assetIdShort}`.replace(
                    `{${'assetIdShort'}}`,
                    encodeURIComponent(String(requestParameters['assetIdShort'])),
                ),
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Generates a set of ids which is used to create a new AAS. Response contains: - AasId - AasIdShort - AssetId - AssetIdShort
     */
    async idGeneratorGenerateIds(
        requestParameters: IdGeneratorGenerateIdsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<AasIds> {
        const response = await this.idGeneratorGenerateIdsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generates a set of ids which is used to create a new AAS. Response contains: - AasId - AasIdShort - AssetId - AssetIdShort
     */
    async idGeneratorGenerateIds2Raw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<AasIds>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/api/IdGenerator/aasIds`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Generates a set of ids which is used to create a new AAS. Response contains: - AasId - AasIdShort - AssetId - AssetIdShort
     */
    async idGeneratorGenerateIds2(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AasIds> {
        const response = await this.idGeneratorGenerateIds2Raw(initOverrides);
        return await response.value();
    }

    /**
     * Generates submodel ids as configured in MnestixIdGeneratorSettings.
     */
    async idGeneratorGenerateSubmodelIdsRaw(
        requestParameters: IdGeneratorGenerateSubmodelIdsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['count'] == null) {
            throw new runtime.RequiredError(
                'count',
                'Required parameter "count" was null or undefined when calling idGeneratorGenerateSubmodelIds().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/api/IdGenerator/submodelIds/{count}`.replace(
                    `{${'count'}}`,
                    encodeURIComponent(String(requestParameters['count'])),
                ),
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Generates submodel ids as configured in MnestixIdGeneratorSettings.
     */
    async idGeneratorGenerateSubmodelIds(
        requestParameters: IdGeneratorGenerateSubmodelIdsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<string>> {
        const response = await this.idGeneratorGenerateSubmodelIdsRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
