version: 2
updates:
  # biweekly minor+patch and major
  - package-ecosystem: npm
    target-branch: dev
    directory: "/"
    schedule:
      interval: cron
      cronjob: "0 8 * * mon%2"
      timezone: "Europe/Berlin"
    groups:
      yarn-minor-patch:
        update-types: ["patch", "minor"]
      yarn-major:
        update-types: ["major"]
  # monthly docker docker-compose github-actions
  - package-ecosystem: "docker"
    target-branch: dev
    directory: "/"
    groups:
      docker-all:
        patterns:
          - "*"
    schedule:
      interval: cron
      cronjob: "0 8 * * mon%4"
      timezone: "Europe/Berlin"
  - package-ecosystem: docker-compose
    target-branch: dev
    directory: "/"
    groups:
      compose-all:
        patterns:
          - "*"
    schedule:
      interval: cron
      cronjob: "0 8 * * mon%4"
      timezone: "Europe/Berlin"
  - package-ecosystem: github-actions
    target-branch: dev
    directory: "/"
    groups:
      actions-all:
        patterns:
          - "*"
    schedule:
      interval: cron
      cronjob: "0 8 * * mon%4"
      timezone: "Europe/Berlin"
