networks:
  mnestix-network:
    driver: bridge
    name: mnestix-network

volumes:
  mnestix-database:
  basyx-db-data:

services:
  mnestix-browser:
    container_name: mnestix-browser
    image: mnestix/mnestix-browser:2.2.0
    profiles: ["", "frontend", "tests"]
    build:
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      REGISTRY_API_URL: "https://mnestix-proxy:5065/registry" # 'https://registry.dpp40-2-v2.industrialdigitaltwin.org/'
      SUBMODEL_REGISTRY_API_URL: "http://mnestix-proxy:5065/registry" # 'https://submodel-registry.dpp40-2-v2.industrialdigitaltwin.org/'
      DISCOVERY_API_URL: "http://mnestix-proxy:5065/discovery"
      AAS_REPO_API_URL: "http://mnestix-proxy:5065/repo"
      SUBMODEL_REPO_API_URL: "http://mnestix-proxy:5065/repo"
      CONCEPT_DESCRIPTION_REPO_API_URL: "http://mnestix-proxy:5065/repo"
      SERIALIZATION_API_URL: "http://mnestix-proxy:5065/repo"
      MNESTIX_AAS_GENERATOR_API_URL: "http://mnestix-proxy:5065"
      MNESTIX_BACKEND_API_KEY: ${MNESTIX_BACKEND_API_KEY:-verySecureApiKey}
      AAS_LIST_FEATURE_FLAG: "true"
      TRANSFER_FEATURE_FLAG: "false"
      COMPARISON_FEATURE_FLAG: "true"
      EXPERIMENTAL_PRODUCT_VIEW_FEATURE_FLAG: "false"
      AUTHENTICATION_FEATURE_FLAG: "false"
      LOCK_TIMESERIES_PERIOD_FEATURE_FLAG: "true"
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-verySecureNextAuthSecret}
      SECRET_ENC_KEY: ${SECRET_ENC_KEY:-J+mMxwKo+aoFJ6uxMv6Acv54buuBir2EJ3z6LGFB+Vo=} # needs to be secure, can be generated by: node -e "console.log(require('crypto').randomBytes(32).toString('base64'))"
      IMPRINT_URL: ""
      DATA_PRIVACY_URL: ""
      BASYX_RBAC_ENABLED: "false"
    networks:
      - mnestix-network
    volumes:
      - mnestix-database:/app/prisma/database

  mnestix-proxy:
    image: mnestix/mnestix-proxy:dev
    container_name: mnestix-proxy
    profiles: ["", "proxy", "backend", "tests"]
    ports:
      - "5065:5065"
    environment:
      # API key authorization
      CustomerEndpointsSecurity__ApiKey: ${MNESTIX_BACKEND_API_KEY:-verySecureApiKey}
      # Connection to Repository Service:
      ReverseProxy__Clusters__mnestixApiCluster__Destinations__destination1__Address: "http://mnestix-aas-generator:5064/"
      ReverseProxy__Clusters__aasRepoCluster__Destinations__destination1__Address: "http://aas-repository:8081/"
      ReverseProxy__Clusters__submodelRepoCluster__Destinations__destination1__Address: "http://submodel-repository:8081/"
      ReverseProxy__Clusters__conceptDescriptionRepoCluster__Destinations__destination1__Address: "http://concept-description-repository:8081/"
      ReverseProxy__Clusters__aasRegistryCluster__Destinations__destination1__Address: "http://aas-registry:8081/"
      ReverseProxy__Clusters__submodelRegistryCluster__Destinations__destination1__Address: "http://submodel-registry:8081/"
      ReverseProxy__Clusters__discoveryCluster__Destinations__destination1__Address: "http://aas-discovery:8081/"
      # InfluxDB Configuration
      # URL to specify the host and port where InfluxDB is running:
      ReverseProxy__Clusters__influxCluster__Destinations__destination1__Address: "http://example/"
      # Token:
      ReverseProxy__Routes__InfluxRoute__Transforms__1__Set: "Token "
      # ASP.NET Core URLs
      ASPNETCORE_URLS: "http://+:5065"
    depends_on:
      aas-repository:
        condition: service_healthy
      submodel-repository:
        condition: service_healthy
      aas-discovery:
        condition: service_healthy
    networks:
      - mnestix-network

  mnestix-aas-generator:
    image: mnestix/mnestix-aas-generator:dev
    container_name: mnestix-aas-generator
    profiles: ["", "backend", "tests"]
    environment:
      # API key authorization
      CustomerEndpointsSecurity__ApiKey: ${MNESTIX_BACKEND_API_KEY:-verySecureApiKey}
      # Features Configuration
      Features__UseAuthentication: "false"
      # ASP.NET Core URLs
      ASPNETCORE_URLS: "http://+:5064"
      # ServerUrls
      ServerUrls: "http://mnestix-proxy:5065/repo/"
    depends_on:
      aas-repository:
        condition: service_healthy # only after the healthcheck in aas is successful, the mnestix container is being created
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    networks:
      - mnestix-network

  basyx-db:
    image: postgres:16-alpine
    container_name: basyx-db
    profiles: ["", "basyx", "tests"]
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=basyx
      - POSTGRES_PASSWORD=basyx
      - POSTGRES_DB=basyxdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U basyx -d basyxdb"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - basyx-db-data:/var/lib/postgresql/data
    networks:
      - mnestix-network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"


  aas-repository:
    image: eclipsebasyx/aasrepository-go:1.0.0-rc.1
    container_name: aas-repository
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - POSTGRES_HOST=basyx-db
      - POSTGRES_PORT=5432
      - POSTGRES_DBNAME=basyxdb
      - POSTGRES_USER=basyx
      - POSTGRES_PASSWORD=basyx
      - CORS_ALLOWEDORIGINS=*
      - CORS_ALLOWEDMETHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - CORS_ALLOWEDHEADERS=*
      - CORS_ALLOWEDCREDENTIALS=true
      - ABAC_ENABLED=false
    depends_on:
      basyx-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/healthprobe"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    restart: unless-stopped
    networks:
      - mnestix-network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

  submodel-repository:
    image: eclipsebasyx/submodelrepository-go:1.0.0-rc.1
    container_name: submodel-repository
    ports:
      - "8082:8081"
    environment:
      - SERVER_PORT=8081
      - POSTGRES_HOST=basyx-db
      - POSTGRES_PORT=5432
      - POSTGRES_DBNAME=basyxdb
      - POSTGRES_USER=basyx
      - POSTGRES_PASSWORD=basyx
      - CORS_ALLOWEDORIGINS=*
      - CORS_ALLOWEDMETHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - CORS_ALLOWEDHEADERS=*
      - CORS_ALLOWEDCREDENTIALS=true
      - ABAC_ENABLED=false
    depends_on:
      basyx-db:
        condition: service_healthy
      aas-repository:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/healthprobe"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    restart: unless-stopped
    networks:
      - mnestix-network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

  concept-description-repository:
    image: eclipsebasyx/conceptdescriptionrepository-go:1.0.0-rc.1
    container_name: concept-description-repository
    ports:
      - "8083:8081"
    environment:
      - SERVER_PORT=8081
      - POSTGRES_HOST=basyx-db
      - POSTGRES_PORT=5432
      - POSTGRES_DBNAME=basyxdb
      - POSTGRES_USER=basyx
      - POSTGRES_PASSWORD=basyx
      - CORS_ALLOWEDORIGINS=*
      - CORS_ALLOWEDMETHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - CORS_ALLOWEDHEADERS=*
      - CORS_ALLOWEDCREDENTIALS=true
      - ABAC_ENABLED=false
    depends_on:
      basyx-db:
        condition: service_healthy
      aas-repository:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/healthprobe"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    restart: unless-stopped
    networks:
      - mnestix-network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"

  aas-registry:
    image: eclipsebasyx/aasregistry-go:1.0.0-rc.1
    container_name: aas-registry
    ports:
      - "8084:8081"
    depends_on:
      basyx-db:
        condition: service_healthy
      aas-repository:
        condition: service_healthy
    environment:
      - SERVER_PORT=8081
      - POSTGRES_HOST=basyx-db
      - POSTGRES_PORT=5432
      - POSTGRES_DBNAME=basyxdb
      - POSTGRES_USER=basyx
      - POSTGRES_PASSWORD=basyx
      - CORS_ALLOWEDORIGINS=*
      - CORS_ALLOWEDMETHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - CORS_ALLOWEDHEADERS=*
      - CORS_ALLOWEDCREDENTIALS=true
      - ABAC_ENABLED=false
    healthcheck: # check the endpoint for a valid response (service ready)
      test: curl -f http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      retries: 6
    networks:
      - mnestix-network

  submodel-registry:
    image: eclipsebasyx/submodelregistry-go:1.0.0-rc.1
    container_name: submodel-registry
    ports:
      - "8085:8081"
    depends_on:
      basyx-db:
        condition: service_healthy
      aas-repository:
        condition: service_healthy
    environment:
      - SERVER_PORT=8081
      - POSTGRES_HOST=basyx-db
      - POSTGRES_PORT=5432
      - POSTGRES_DBNAME=basyxdb
      - POSTGRES_USER=basyx
      - POSTGRES_PASSWORD=basyx
      - CORS_ALLOWEDORIGINS=*
      - CORS_ALLOWEDMETHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - CORS_ALLOWEDHEADERS=*
      - CORS_ALLOWEDCREDENTIALS=true
      - ABAC_ENABLED=false
    healthcheck: # check the endpoint for a valid response (service ready)
      test: curl -f http://localhost:8080/actuator/health
      interval: 10s
      timeout: 10s
      retries: 6
    networks:
      - mnestix-network

  aas-discovery:
    image: eclipsebasyx/aasdiscovery-go:1.0.0-rc.1
    container_name: aas-discovery
    ports:
      - "8086:8081"
    environment:
      - SERVER_PORT=8081
      - POSTGRES_HOST=basyx-db
      - POSTGRES_PORT=5432
      - POSTGRES_DBNAME=basyxdb
      - POSTGRES_USER=basyx
      - POSTGRES_PASSWORD=basyx
      - CORS_ALLOWEDORIGINS=*
      - CORS_ALLOWEDMETHODS=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - CORS_ALLOWEDHEADERS=*
      - CORS_ALLOWEDCREDENTIALS=true
      - ABAC_ENABLED=false
    depends_on:
      basyx-db:
        condition: service_healthy
      aas-repository:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/healthprobe"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    restart: unless-stopped
    networks:
      - mnestix-network
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"