services:
  mnestix-proxy:
    environment:
      # OpenID Configuration
      OpenId__EnableOpenIdAuth: 'true'
      OpenId__Issuer: 'http://keycloak:8080/realms/Mnestix'
      OpenId__ClientID: 'mnestixApi-demo'
      OpenId__RequireHttpsMetadata: 'false'
