/* tslint:disable */
/* eslint-disable */
/**
 * Mnestix AAS Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@xitaso.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { CreateAasResponse, ProblemDetails } from '../models/index';

export interface AasCreatorCreateAasRequest {
    assetIdShort: string;
    xApiVersion?: string;
}

/**
 * AasCreatorApi - interface
 *
 * @export
 * @interface AasCreatorApiInterface
 */
export interface AasCreatorApiInterface {
    /**
     *
     * @summary Creates a new AAS for a given assetIdShort. Response contains id of the newly generated AAS Base64UrlEncoded.
     * @param {string} assetIdShort The assetIdShort to be used for creating the AAS.
     * @param {string} [xApiVersion]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AasCreatorApiInterface
     */
    aasCreatorCreateAasRaw(
        requestParameters: AasCreatorCreateAasRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<CreateAasResponse>>;

    /**
     * Creates a new AAS for a given assetIdShort. Response contains id of the newly generated AAS Base64UrlEncoded.
     */
    aasCreatorCreateAas(
        requestParameters: AasCreatorCreateAasRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<CreateAasResponse>;
}

/**
 *
 */
export class AasCreatorApi extends runtime.BaseAPI implements AasCreatorApiInterface {
    /**
     * Creates a new AAS for a given assetIdShort. Response contains id of the newly generated AAS Base64UrlEncoded.
     */
    async aasCreatorCreateAasRaw(
        requestParameters: AasCreatorCreateAasRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<CreateAasResponse>> {
        if (requestParameters['assetIdShort'] == null) {
            throw new runtime.RequiredError(
                'assetIdShort',
                'Required parameter "assetIdShort" was null or undefined when calling aasCreatorCreateAas().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xApiVersion'] != null) {
            headerParameters['x-api-version'] = String(requestParameters['xApiVersion']);
        }

        const response = await this.request(
            {
                path: `/api/AasCreator/{assetIdShort}`.replace(
                    `{${'assetIdShort'}}`,
                    encodeURIComponent(String(requestParameters['assetIdShort'])),
                ),
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Creates a new AAS for a given assetIdShort. Response contains id of the newly generated AAS Base64UrlEncoded.
     */
    async aasCreatorCreateAas(
        requestParameters: AasCreatorCreateAasRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<CreateAasResponse> {
        const response = await this.aasCreatorCreateAasRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
