/* tslint:disable */
/* eslint-disable */
/**
 * Mnestix AAS Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@xitaso.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { Aas, ProblemDetails } from '../models/index';

export interface AasRelationshipGetDerivedFromRequest {
    aasId?: string;
    xApiVersion?: string;
}

/**
 * AasRelationshipApi - interface
 *
 * @export
 * @interface AasRelationshipApiInterface
 */
export interface AasRelationshipApiInterface {
    /**
     *
     * @summary Returns all asset administration shells that have a direct derivedFrom dependency on the given asset administration shell
     * @param {string} [aasId] The Id of the AAS to search inheritors for
     * @param {string} [xApiVersion]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AasRelationshipApiInterface
     */
    aasRelationshipGetDerivedFromRaw(
        requestParameters: AasRelationshipGetDerivedFromRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<Aas>>>;

    /**
     * Returns all asset administration shells that have a direct derivedFrom dependency on the given asset administration shell
     */
    aasRelationshipGetDerivedFrom(
        requestParameters: AasRelationshipGetDerivedFromRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<Aas>>;
}

/**
 *
 */
export class AasRelationshipApi extends runtime.BaseAPI implements AasRelationshipApiInterface {
    /**
     * Returns all asset administration shells that have a direct derivedFrom dependency on the given asset administration shell
     */
    async aasRelationshipGetDerivedFromRaw(
        requestParameters: AasRelationshipGetDerivedFromRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<Aas>>> {
        const queryParameters: any = {};

        if (requestParameters['aasId'] != null) {
            queryParameters['aasId'] = requestParameters['aasId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xApiVersion'] != null) {
            headerParameters['x-api-version'] = String(requestParameters['xApiVersion']);
        }

        const response = await this.request(
            {
                path: `/api/AasRelationship/GetDerivedFrom`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns all asset administration shells that have a direct derivedFrom dependency on the given asset administration shell
     */
    async aasRelationshipGetDerivedFrom(
        requestParameters: AasRelationshipGetDerivedFromRequest = {},
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<Aas>> {
        const response = await this.aasRelationshipGetDerivedFromRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
