/* tslint:disable */
/* eslint-disable */
/**
 * Mnestix AAS Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@xitaso.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ProblemDetails } from '../models/index';

export interface ConfigurationGetIdConfigurationRequest {
    xApiVersion?: string;
}

export interface ConfigurationPatchIdConfigurationRequest {
    idShortPath?: string;
    value?: string;
    xApiVersion?: string;
}

/**
 * ConfigurationApi - interface
 *
 * @export
 * @interface ConfigurationApiInterface
 */
export interface ConfigurationApiInterface {
    /**
     *
     * @summary Retrieves the current ID generation configuration settings.
     * @param {string} [xApiVersion]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConfigurationApiInterface
     */
    configurationGetIdConfigurationRaw(
        requestParameters: ConfigurationGetIdConfigurationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     * Retrieves the current ID generation configuration settings.
     */
    configurationGetIdConfiguration(
        requestParameters: ConfigurationGetIdConfigurationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;

    /**
     *
     * @summary Applies a partial update to a specific ID generation configuration value.
     * @param {string} [idShortPath] The path to the setting within the submodel elements.
     * @param {string} [value] The new value to apply.
     * @param {string} [xApiVersion]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ConfigurationApiInterface
     */
    configurationPatchIdConfigurationRaw(
        requestParameters: ConfigurationPatchIdConfigurationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     * Applies a partial update to a specific ID generation configuration value.
     */
    configurationPatchIdConfiguration(
        requestParameters: ConfigurationPatchIdConfigurationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;
}

/**
 *
 */
export class ConfigurationApi extends runtime.BaseAPI implements ConfigurationApiInterface {
    /**
     * Retrieves the current ID generation configuration settings.
     */
    async configurationGetIdConfigurationRaw(
        requestParameters: ConfigurationGetIdConfigurationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xApiVersion'] != null) {
            headerParameters['x-api-version'] = String(requestParameters['xApiVersion']);
        }

        const response = await this.request(
            {
                path: `/api/Configuration`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Retrieves the current ID generation configuration settings.
     */
    async configurationGetIdConfiguration(
        requestParameters: ConfigurationGetIdConfigurationRequest = {},
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.configurationGetIdConfigurationRaw(requestParameters, initOverrides);
    }

    /**
     * Applies a partial update to a specific ID generation configuration value.
     */
    async configurationPatchIdConfigurationRaw(
        requestParameters: ConfigurationPatchIdConfigurationRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['idShortPath'] != null) {
            queryParameters['idShortPath'] = requestParameters['idShortPath'];
        }

        if (requestParameters['value'] != null) {
            queryParameters['value'] = requestParameters['value'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xApiVersion'] != null) {
            headerParameters['x-api-version'] = String(requestParameters['xApiVersion']);
        }

        const response = await this.request(
            {
                path: `/api/Configuration`,
                method: 'PATCH',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Applies a partial update to a specific ID generation configuration value.
     */
    async configurationPatchIdConfiguration(
        requestParameters: ConfigurationPatchIdConfigurationRequest = {},
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.configurationPatchIdConfigurationRaw(requestParameters, initOverrides);
    }
}
