/* tslint:disable */
/* eslint-disable */
/**
 * Mnestix AAS Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@xitaso.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { AasIds } from '../models/index';

export interface IdGeneratorGenerateIdsRequest {
    assetIdShort: string;
    xApiVersion?: string;
}

export interface IdGeneratorGenerateIds2Request {
    xApiVersion?: string;
}

export interface IdGeneratorGenerateSubmodelIdsRequest {
    count: number;
    xApiVersion?: string;
}

/**
 * IdGeneratorApi - interface
 *
 * @export
 * @interface IdGeneratorApiInterface
 */
export interface IdGeneratorApiInterface {
    /**
     *
     * @summary Generates a set of ids which is used to create a new AAS. Response contains: - AasId - AasIdShort - AssetId - AssetIdShort
     * @param {string} assetIdShort The assetIdShort which must be used for generating ids.
     * @param {string} [xApiVersion]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IdGeneratorApiInterface
     */
    idGeneratorGenerateIdsRaw(
        requestParameters: IdGeneratorGenerateIdsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<AasIds>>;

    /**
     * Generates a set of ids which is used to create a new AAS. Response contains: - AasId - AasIdShort - AssetId - AssetIdShort
     */
    idGeneratorGenerateIds(
        requestParameters: IdGeneratorGenerateIdsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<AasIds>;

    /**
     *
     * @summary Generates a set of ids which is used to create a new AAS. Response contains: - AasId - AasIdShort - AssetId - AssetIdShort
     * @param {string} [xApiVersion]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IdGeneratorApiInterface
     */
    idGeneratorGenerateIds2Raw(
        requestParameters: IdGeneratorGenerateIds2Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<AasIds>>;

    /**
     * Generates a set of ids which is used to create a new AAS. Response contains: - AasId - AasIdShort - AssetId - AssetIdShort
     */
    idGeneratorGenerateIds2(
        requestParameters: IdGeneratorGenerateIds2Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<AasIds>;

    /**
     *
     * @summary Generates submodel ids as configured in MnestixIdGeneratorSettings.
     * @param {number} count Amount of submodels id to be generated.
     * @param {string} [xApiVersion]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IdGeneratorApiInterface
     */
    idGeneratorGenerateSubmodelIdsRaw(
        requestParameters: IdGeneratorGenerateSubmodelIdsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<string>>>;

    /**
     * Generates submodel ids as configured in MnestixIdGeneratorSettings.
     */
    idGeneratorGenerateSubmodelIds(
        requestParameters: IdGeneratorGenerateSubmodelIdsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<string>>;
}

/**
 *
 */
export class IdGeneratorApi extends runtime.BaseAPI implements IdGeneratorApiInterface {
    /**
     * Generates a set of ids which is used to create a new AAS. Response contains: - AasId - AasIdShort - AssetId - AssetIdShort
     */
    async idGeneratorGenerateIdsRaw(
        requestParameters: IdGeneratorGenerateIdsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<AasIds>> {
        if (requestParameters['assetIdShort'] == null) {
            throw new runtime.RequiredError(
                'assetIdShort',
                'Required parameter "assetIdShort" was null or undefined when calling idGeneratorGenerateIds().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xApiVersion'] != null) {
            headerParameters['x-api-version'] = String(requestParameters['xApiVersion']);
        }

        const response = await this.request(
            {
                path: `/api/IdGenerator/aasIds/{assetIdShort}`.replace(
                    `{${'assetIdShort'}}`,
                    encodeURIComponent(String(requestParameters['assetIdShort'])),
                ),
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Generates a set of ids which is used to create a new AAS. Response contains: - AasId - AasIdShort - AssetId - AssetIdShort
     */
    async idGeneratorGenerateIds(
        requestParameters: IdGeneratorGenerateIdsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<AasIds> {
        const response = await this.idGeneratorGenerateIdsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generates a set of ids which is used to create a new AAS. Response contains: - AasId - AasIdShort - AssetId - AssetIdShort
     */
    async idGeneratorGenerateIds2Raw(
        requestParameters: IdGeneratorGenerateIds2Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<AasIds>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xApiVersion'] != null) {
            headerParameters['x-api-version'] = String(requestParameters['xApiVersion']);
        }

        const response = await this.request(
            {
                path: `/api/IdGenerator/aasIds`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Generates a set of ids which is used to create a new AAS. Response contains: - AasId - AasIdShort - AssetId - AssetIdShort
     */
    async idGeneratorGenerateIds2(
        requestParameters: IdGeneratorGenerateIds2Request = {},
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<AasIds> {
        const response = await this.idGeneratorGenerateIds2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generates submodel ids as configured in MnestixIdGeneratorSettings.
     */
    async idGeneratorGenerateSubmodelIdsRaw(
        requestParameters: IdGeneratorGenerateSubmodelIdsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['count'] == null) {
            throw new runtime.RequiredError(
                'count',
                'Required parameter "count" was null or undefined when calling idGeneratorGenerateSubmodelIds().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xApiVersion'] != null) {
            headerParameters['x-api-version'] = String(requestParameters['xApiVersion']);
        }

        const response = await this.request(
            {
                path: `/api/IdGenerator/submodelIds/{count}`.replace(
                    `{${'count'}}`,
                    encodeURIComponent(String(requestParameters['count'])),
                ),
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Generates submodel ids as configured in MnestixIdGeneratorSettings.
     */
    async idGeneratorGenerateSubmodelIds(
        requestParameters: IdGeneratorGenerateSubmodelIdsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Array<string>> {
        const response = await this.idGeneratorGenerateSubmodelIdsRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
