name: 'Setup Build Environment'
description: 'Restore caches, checkout repo, setup QEMU, Buildx, and Docker login'
inputs:
  docker_username:
    description: 'Docker username'
    required: true
  docker_password:
    description: 'Docker password or token'
    required: true
outputs:
  branch:
    description: 'Extracted branch name'
    value: ${{ steps.extract_branch.outputs.branch }}

runs:
  using: 'composite'

  steps:
    - name: Restore amd64 cache
      uses: actions/cache/restore@v4
      with:
        path: |
          /tmp/buildx-amd64-cache
        key: buildx-amd64-${{ github.ref }}-${{ github.run_id }}
        # can be build without cache
        fail-on-cache-miss: false

    - name: Restore arm64 cache
      uses: actions/cache/restore@v4
      with:
        path: |
          /tmp/buildx-arm64-cache
        key: buildx-arm64-${{ github.ref }}-${{ github.run_id }}
        # building takes ages
        fail-on-cache-miss: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Extract branch name
      id: extract_branch
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      shell: bash
