/* tslint:disable */
/* eslint-disable */
/**
 * Mnestix AAS Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@xitaso.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ProblemDetails } from '../models/index';

export interface CustomTemplatesGetCustomSubmodelRequest {
    base64EncodedCustomTemplateId: string;
}

/**
 * CustomTemplatesApi - interface
 *
 * @export
 * @interface CustomTemplatesApiInterface
 */
export interface CustomTemplatesApiInterface {
    /**
     *
     * @summary Returns all submodel templates from the custom templates AAS.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomTemplatesApiInterface
     */
    customTemplatesGetAllCustomSubmodelsRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     * Returns all submodel templates from the custom templates AAS.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    customTemplatesGetAllCustomSubmodels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     *
     * @summary Returns the submodel template from the custom templates AAS with the specified shortId.
     * @param {string} base64EncodedCustomTemplateId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomTemplatesApiInterface
     */
    customTemplatesGetCustomSubmodelRaw(
        requestParameters: CustomTemplatesGetCustomSubmodelRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     * Returns the submodel template from the custom templates AAS with the specified shortId.
     */
    customTemplatesGetCustomSubmodel(
        requestParameters: CustomTemplatesGetCustomSubmodelRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;
}

/**
 *
 */
export class CustomTemplatesApi extends runtime.BaseAPI implements CustomTemplatesApiInterface {
    /**
     * Returns all submodel templates from the custom templates AAS.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    async customTemplatesGetAllCustomSubmodelsRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY'] = await this.configuration.apiKey('X-API-KEY'); // ApiKey authentication
        }

        const response = await this.request(
            {
                path: `/api/v1/CustomTemplates`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Returns all submodel templates from the custom templates AAS.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    async customTemplatesGetAllCustomSubmodels(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.customTemplatesGetAllCustomSubmodelsRaw(initOverrides);
    }

    /**
     * Returns the submodel template from the custom templates AAS with the specified shortId.
     */
    async customTemplatesGetCustomSubmodelRaw(
        requestParameters: CustomTemplatesGetCustomSubmodelRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['base64EncodedCustomTemplateId'] == null) {
            throw new runtime.RequiredError(
                'base64EncodedCustomTemplateId',
                'Required parameter "base64EncodedCustomTemplateId" was null or undefined when calling customTemplatesGetCustomSubmodel().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY'] = await this.configuration.apiKey('X-API-KEY'); // ApiKey authentication
        }

        const response = await this.request(
            {
                path: `/api/v1/CustomTemplates/{base64EncodedCustomTemplateId}`.replace(
                    `{${'base64EncodedCustomTemplateId'}}`,
                    encodeURIComponent(String(requestParameters['base64EncodedCustomTemplateId'])),
                ),
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Returns the submodel template from the custom templates AAS with the specified shortId.
     */
    async customTemplatesGetCustomSubmodel(
        requestParameters: CustomTemplatesGetCustomSubmodelRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.customTemplatesGetCustomSubmodelRaw(requestParameters, initOverrides);
    }
}
