/* tslint:disable */
/* eslint-disable */
/**
 * Mnestix AAS Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@xitaso.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface DefaultTemplatesAddDefaultSubmodelTemplateRequest {
    body: any | null;
    apiVersion?: string;
}

/**
 * DefaultTemplatesApi - interface
 *
 * @export
 * @interface DefaultTemplatesApiInterface
 */
export interface DefaultTemplatesApiInterface {
    /**
     *
     * @summary Creates a new custom template in the custom templates AAS. Submodel Id needs to be unique and present in JSON body.
     * @param {any} body The submodel template to add as json.
     * @param {string} [apiVersion]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultTemplatesApiInterface
     */
    defaultTemplatesAddDefaultSubmodelTemplateRaw(
        requestParameters: DefaultTemplatesAddDefaultSubmodelTemplateRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Blob>>;

    /**
     * Creates a new custom template in the custom templates AAS. Submodel Id needs to be unique and present in JSON body.
     */
    defaultTemplatesAddDefaultSubmodelTemplate(
        requestParameters: DefaultTemplatesAddDefaultSubmodelTemplateRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Blob>;
}

/**
 *
 */
export class DefaultTemplatesApi extends runtime.BaseAPI implements DefaultTemplatesApiInterface {
    /**
     * Creates a new custom template in the custom templates AAS. Submodel Id needs to be unique and present in JSON body.
     */
    async defaultTemplatesAddDefaultSubmodelTemplateRaw(
        requestParameters: DefaultTemplatesAddDefaultSubmodelTemplateRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling defaultTemplatesAddDefaultSubmodelTemplate().',
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY'] = await this.configuration.apiKey('X-API-KEY'); // Bearer-Token authentication
        }

        const response = await this.request(
            {
                path: `/api/DefaultTemplates`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters['body'] as any,
            },
            initOverrides,
        );

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Creates a new custom template in the custom templates AAS. Submodel Id needs to be unique and present in JSON body.
     */
    async defaultTemplatesAddDefaultSubmodelTemplate(
        requestParameters: DefaultTemplatesAddDefaultSubmodelTemplateRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Blob> {
        const response = await this.defaultTemplatesAddDefaultSubmodelTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
