/* tslint:disable */
/* eslint-disable */
/**
 * Mnestix AAS Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@xitaso.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ProblemDetails } from '../models/index';

export interface TemplateCreateCustomSubmodelRequest {
    body: any | null;
    apiVersion?: string;
}

export interface TemplateGetAllDefaultSubmodelsRequest {
    apiVersion?: string;
}

/**
 * TemplateApi - interface
 *
 * @export
 * @interface TemplateApiInterface
 */
export interface TemplateApiInterface {
    /**
     *
     * @summary ONLY FOR INTERNAL USAGE. BearerToken needed. Creates a new custom template in the custom templates AAS of the given submodel semantic id.
     * @param {any} body The default submodel as json string
     * @param {string} [apiVersion]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplateApiInterface
     */
    templateCreateCustomSubmodelRaw(
        requestParameters: TemplateCreateCustomSubmodelRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<string>>;

    /**
     * ONLY FOR INTERNAL USAGE. BearerToken needed. Creates a new custom template in the custom templates AAS of the given submodel semantic id.
     */
    templateCreateCustomSubmodel(
        requestParameters: TemplateCreateCustomSubmodelRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<string>;

    /**
     *
     * @summary ONLY FOR INTERNAL USAGE. BearerToken needed. Returns all default submodel templates from the default templates AAS.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     * @param {string} [apiVersion]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplateApiInterface
     */
    templateGetAllDefaultSubmodelsRaw(
        requestParameters: TemplateGetAllDefaultSubmodelsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     * ONLY FOR INTERNAL USAGE. BearerToken needed. Returns all default submodel templates from the default templates AAS.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    templateGetAllDefaultSubmodels(
        requestParameters: TemplateGetAllDefaultSubmodelsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;
}

/**
 *
 */
export class TemplateApi extends runtime.BaseAPI implements TemplateApiInterface {
    /**
     * ONLY FOR INTERNAL USAGE. BearerToken needed. Creates a new custom template in the custom templates AAS of the given submodel semantic id.
     */
    async templateCreateCustomSubmodelRaw(
        requestParameters: TemplateCreateCustomSubmodelRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling templateCreateCustomSubmodel().',
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request(
            {
                path: `/api/Template/createCustomSubmodel`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters['body'] as any,
            },
            initOverrides,
        );

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * ONLY FOR INTERNAL USAGE. BearerToken needed. Creates a new custom template in the custom templates AAS of the given submodel semantic id.
     */
    async templateCreateCustomSubmodel(
        requestParameters: TemplateCreateCustomSubmodelRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<string> {
        const response = await this.templateCreateCustomSubmodelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ONLY FOR INTERNAL USAGE. BearerToken needed. Returns all default submodel templates from the default templates AAS.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    async templateGetAllDefaultSubmodelsRaw(
        requestParameters: TemplateGetAllDefaultSubmodelsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/api/Template/allDefaultSubmodels`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ONLY FOR INTERNAL USAGE. BearerToken needed. Returns all default submodel templates from the default templates AAS.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    async templateGetAllDefaultSubmodels(
        requestParameters: TemplateGetAllDefaultSubmodelsRequest = {},
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.templateGetAllDefaultSubmodelsRaw(requestParameters, initOverrides);
    }
}
