/* tslint:disable */
/* eslint-disable */
/**
 * Mnestix AAS Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@xitaso.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ProblemDetails } from '../models/index';

export interface BlueprintsCreateBlueprintRequest {
    body: any | null;
}

export interface BlueprintsDeleteBlueprintRequest {
    base64EncodedBlueprintId: string;
}

export interface BlueprintsGetBlueprintByIdRequest {
    base64EncodedBlueprintId: string;
}

export interface BlueprintsUpdateBlueprintRequest {
    submodelId: string;
    body: any | null;
}

/**
 * BlueprintsApi - interface
 *
 * @export
 * @interface BlueprintsApiInterface
 */
export interface BlueprintsApiInterface {
    /**
     *
     * @summary Creates a new blueprint of the given submodel semantic id.
     * @param {any} body The blueprint as json string
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlueprintsApiInterface
     */
    blueprintsCreateBlueprintRaw(
        requestParameters: BlueprintsCreateBlueprintRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<string>>;

    /**
     * Creates a new blueprint of the given submodel semantic id.
     */
    blueprintsCreateBlueprint(
        requestParameters: BlueprintsCreateBlueprintRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<string>;

    /**
     *
     * @summary Deletes a blueprint identified by the base64-encoded template ID.
     * @param {string} base64EncodedBlueprintId A base64-encoded string representing the unique identifier of the blueprint to be deleted.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlueprintsApiInterface
     */
    blueprintsDeleteBlueprintRaw(
        requestParameters: BlueprintsDeleteBlueprintRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     * Deletes a blueprint identified by the base64-encoded template ID.
     */
    blueprintsDeleteBlueprint(
        requestParameters: BlueprintsDeleteBlueprintRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;

    /**
     *
     * @summary Returns all blueprints. This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlueprintsApiInterface
     */
    blueprintsGetAllBlueprintsRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     * Returns all blueprints. This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    blueprintsGetAllBlueprints(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     *
     * @summary Returns the blueprint with the specified shortId.
     * @param {string} base64EncodedBlueprintId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlueprintsApiInterface
     */
    blueprintsGetBlueprintByIdRaw(
        requestParameters: BlueprintsGetBlueprintByIdRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     * Returns the blueprint with the specified shortId.
     */
    blueprintsGetBlueprintById(
        requestParameters: BlueprintsGetBlueprintByIdRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;

    /**
     *
     * @summary Updates a blueprint.
     * @param {string} submodelId The id of the submodel
     * @param {any} body The blueprint to update as json string
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlueprintsApiInterface
     */
    blueprintsUpdateBlueprintRaw(
        requestParameters: BlueprintsUpdateBlueprintRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     * Updates a blueprint.
     */
    blueprintsUpdateBlueprint(
        requestParameters: BlueprintsUpdateBlueprintRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;
}

/**
 *
 */
export class BlueprintsApi extends runtime.BaseAPI implements BlueprintsApiInterface {
    /**
     * Creates a new blueprint of the given submodel semantic id.
     */
    async blueprintsCreateBlueprintRaw(
        requestParameters: BlueprintsCreateBlueprintRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling blueprintsCreateBlueprint().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY'] = await this.configuration.apiKey('X-API-KEY'); // ApiKey authentication
        }

        const response = await this.request(
            {
                path: `/api/v2/Blueprints`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters['body'] as any,
            },
            initOverrides,
        );

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Creates a new blueprint of the given submodel semantic id.
     */
    async blueprintsCreateBlueprint(
        requestParameters: BlueprintsCreateBlueprintRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<string> {
        const response = await this.blueprintsCreateBlueprintRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes a blueprint identified by the base64-encoded template ID.
     */
    async blueprintsDeleteBlueprintRaw(
        requestParameters: BlueprintsDeleteBlueprintRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['base64EncodedBlueprintId'] == null) {
            throw new runtime.RequiredError(
                'base64EncodedBlueprintId',
                'Required parameter "base64EncodedBlueprintId" was null or undefined when calling blueprintsDeleteBlueprint().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY'] = await this.configuration.apiKey('X-API-KEY'); // ApiKey authentication
        }

        const response = await this.request(
            {
                path: `/api/v2/Blueprints/{base64EncodedBlueprintId}`.replace(
                    `{${'base64EncodedBlueprintId'}}`,
                    encodeURIComponent(String(requestParameters['base64EncodedBlueprintId'])),
                ),
                method: 'DELETE',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes a blueprint identified by the base64-encoded template ID.
     */
    async blueprintsDeleteBlueprint(
        requestParameters: BlueprintsDeleteBlueprintRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.blueprintsDeleteBlueprintRaw(requestParameters, initOverrides);
    }

    /**
     * Returns all blueprints. This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    async blueprintsGetAllBlueprintsRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY'] = await this.configuration.apiKey('X-API-KEY'); // ApiKey authentication
        }

        const response = await this.request(
            {
                path: `/api/v2/Blueprints`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Returns all blueprints. This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    async blueprintsGetAllBlueprints(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.blueprintsGetAllBlueprintsRaw(initOverrides);
    }

    /**
     * Returns the blueprint with the specified shortId.
     */
    async blueprintsGetBlueprintByIdRaw(
        requestParameters: BlueprintsGetBlueprintByIdRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['base64EncodedBlueprintId'] == null) {
            throw new runtime.RequiredError(
                'base64EncodedBlueprintId',
                'Required parameter "base64EncodedBlueprintId" was null or undefined when calling blueprintsGetBlueprintById().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY'] = await this.configuration.apiKey('X-API-KEY'); // ApiKey authentication
        }

        const response = await this.request(
            {
                path: `/api/v2/Blueprints/{base64EncodedBlueprintId}`.replace(
                    `{${'base64EncodedBlueprintId'}}`,
                    encodeURIComponent(String(requestParameters['base64EncodedBlueprintId'])),
                ),
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Returns the blueprint with the specified shortId.
     */
    async blueprintsGetBlueprintById(
        requestParameters: BlueprintsGetBlueprintByIdRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.blueprintsGetBlueprintByIdRaw(requestParameters, initOverrides);
    }

    /**
     * Updates a blueprint.
     */
    async blueprintsUpdateBlueprintRaw(
        requestParameters: BlueprintsUpdateBlueprintRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['submodelId'] == null) {
            throw new runtime.RequiredError(
                'submodelId',
                'Required parameter "submodelId" was null or undefined when calling blueprintsUpdateBlueprint().',
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling blueprintsUpdateBlueprint().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY'] = await this.configuration.apiKey('X-API-KEY'); // ApiKey authentication
        }

        const response = await this.request(
            {
                path: `/api/v2/Blueprints/{submodelId}`.replace(
                    `{${'submodelId'}}`,
                    encodeURIComponent(String(requestParameters['submodelId'])),
                ),
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters['body'] as any,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Updates a blueprint.
     */
    async blueprintsUpdateBlueprint(
        requestParameters: BlueprintsUpdateBlueprintRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.blueprintsUpdateBlueprintRaw(requestParameters, initOverrides);
    }
}
