/* tslint:disable */
/* eslint-disable */
/**
 * Mnestix AAS Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@xitaso.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ProblemDetails } from '../models/index';

export interface BlueprintsCreateBlueprintRequest {
    apiVersion: string | null;
    body: any | null;
}

export interface BlueprintsGetAllBlueprintsRequest {
    apiVersion: string | null;
}

export interface BlueprintsGetBlueprintByIdRequest {
    base64EncodedBlueprintId: string;
    apiVersion: string | null;
}

/**
 * BlueprintsApi - interface
 *
 * @export
 * @interface BlueprintsApiInterface
 */
export interface BlueprintsApiInterface {
    /**
     *
     * @summary ONLY FOR INTERNAL USAGE. BearerToken needed. Creates a new blueprint of the given submodel semantic id.
     * @param {string} apiVersion
     * @param {any} body The blueprint as json string
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlueprintsApiInterface
     */
    blueprintsCreateBlueprintRaw(
        requestParameters: BlueprintsCreateBlueprintRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<string>>;

    /**
     * ONLY FOR INTERNAL USAGE. BearerToken needed. Creates a new blueprint of the given submodel semantic id.
     */
    blueprintsCreateBlueprint(
        requestParameters: BlueprintsCreateBlueprintRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<string>;

    /**
     *
     * @summary Returns all blueprints.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     * @param {string} apiVersion
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlueprintsApiInterface
     */
    blueprintsGetAllBlueprintsRaw(
        requestParameters: BlueprintsGetAllBlueprintsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     * Returns all blueprints.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    blueprintsGetAllBlueprints(
        requestParameters: BlueprintsGetAllBlueprintsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;

    /**
     *
     * @summary Returns the blueprint with the specified shortId.
     * @param {string} base64EncodedBlueprintId
     * @param {string} apiVersion
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BlueprintsApiInterface
     */
    blueprintsGetBlueprintByIdRaw(
        requestParameters: BlueprintsGetBlueprintByIdRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     * Returns the blueprint with the specified shortId.
     */
    blueprintsGetBlueprintById(
        requestParameters: BlueprintsGetBlueprintByIdRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;
}

/**
 *
 */
export class BlueprintsApi extends runtime.BaseAPI implements BlueprintsApiInterface {
    /**
     * ONLY FOR INTERNAL USAGE. BearerToken needed. Creates a new blueprint of the given submodel semantic id.
     */
    async blueprintsCreateBlueprintRaw(
        requestParameters: BlueprintsCreateBlueprintRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['apiVersion'] == null) {
            throw new runtime.RequiredError(
                'apiVersion',
                'Required parameter "apiVersion" was null or undefined when calling blueprintsCreateBlueprint().',
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling blueprintsCreateBlueprint().',
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY'] = await this.configuration.apiKey('X-API-KEY'); // Bearer-Token authentication
        }

        const response = await this.request(
            {
                path: `/api/v2/Blueprints`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters['body'] as any,
            },
            initOverrides,
        );

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * ONLY FOR INTERNAL USAGE. BearerToken needed. Creates a new blueprint of the given submodel semantic id.
     */
    async blueprintsCreateBlueprint(
        requestParameters: BlueprintsCreateBlueprintRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<string> {
        const response = await this.blueprintsCreateBlueprintRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all blueprints.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    async blueprintsGetAllBlueprintsRaw(
        requestParameters: BlueprintsGetAllBlueprintsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['apiVersion'] == null) {
            throw new runtime.RequiredError(
                'apiVersion',
                'Required parameter "apiVersion" was null or undefined when calling blueprintsGetAllBlueprints().',
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY'] = await this.configuration.apiKey('X-API-KEY'); // Bearer-Token authentication
        }

        const response = await this.request(
            {
                path: `/api/v2/Blueprints`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Returns all blueprints.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    async blueprintsGetAllBlueprints(
        requestParameters: BlueprintsGetAllBlueprintsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.blueprintsGetAllBlueprintsRaw(requestParameters, initOverrides);
    }

    /**
     * Returns the blueprint with the specified shortId.
     */
    async blueprintsGetBlueprintByIdRaw(
        requestParameters: BlueprintsGetBlueprintByIdRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['base64EncodedBlueprintId'] == null) {
            throw new runtime.RequiredError(
                'base64EncodedBlueprintId',
                'Required parameter "base64EncodedBlueprintId" was null or undefined when calling blueprintsGetBlueprintById().',
            );
        }

        if (requestParameters['apiVersion'] == null) {
            throw new runtime.RequiredError(
                'apiVersion',
                'Required parameter "apiVersion" was null or undefined when calling blueprintsGetBlueprintById().',
            );
        }

        const queryParameters: any = {};

        if (requestParameters['apiVersion'] != null) {
            queryParameters['api-version'] = requestParameters['apiVersion'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY'] = await this.configuration.apiKey('X-API-KEY'); // Bearer-Token authentication
        }

        const response = await this.request(
            {
                path: `/api/v2/Blueprints/{base64EncodedBlueprintId}`.replace(
                    `{${'base64EncodedBlueprintId'}}`,
                    encodeURIComponent(String(requestParameters['base64EncodedBlueprintId'])),
                ),
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Returns the blueprint with the specified shortId.
     */
    async blueprintsGetBlueprintById(
        requestParameters: BlueprintsGetBlueprintByIdRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.blueprintsGetBlueprintByIdRaw(requestParameters, initOverrides);
    }
}
