/* tslint:disable */
/* eslint-disable */
/**
 * Mnestix AAS Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@xitaso.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ProblemDetails } from '../models/index';

export interface TemplatesCreateTemplateRequest {
    body: any | null;
}

/**
 * TemplatesApi - interface
 *
 * @export
 * @interface TemplatesApiInterface
 */
export interface TemplatesApiInterface {
    /**
     * If SubmodelTemplatesApiUrl is configured, the endpoint returns Status403Forbidden instructing clients to use the remote templates API instead. Otherwise, it logs the payload\'s id and forwards the body to AddNewSubmodelInDefaultTemplateAasAsync.
     * @summary Creates a new template in the templates AAS when the local endpoint is enabled.
     * @param {any} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    templatesCreateTemplateRaw(
        requestParameters: TemplatesCreateTemplateRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<string>>;

    /**
     * If SubmodelTemplatesApiUrl is configured, the endpoint returns Status403Forbidden instructing clients to use the remote templates API instead. Otherwise, it logs the payload\'s id and forwards the body to AddNewSubmodelInDefaultTemplateAasAsync.
     * Creates a new template in the templates AAS when the local endpoint is enabled.
     */
    templatesCreateTemplate(
        requestParameters: TemplatesCreateTemplateRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<string>;

    /**
     *
     * @summary Returns all submodel templates from the templates AAS.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    templatesGetAllTemplatesRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     * Returns all submodel templates from the templates AAS.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    templatesGetAllTemplates(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;
}

/**
 *
 */
export class TemplatesApi extends runtime.BaseAPI implements TemplatesApiInterface {
    /**
     * If SubmodelTemplatesApiUrl is configured, the endpoint returns Status403Forbidden instructing clients to use the remote templates API instead. Otherwise, it logs the payload\'s id and forwards the body to AddNewSubmodelInDefaultTemplateAasAsync.
     * Creates a new template in the templates AAS when the local endpoint is enabled.
     */
    async templatesCreateTemplateRaw(
        requestParameters: TemplatesCreateTemplateRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling templatesCreateTemplate().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY'] = await this.configuration.apiKey('X-API-KEY'); // ApiKey authentication
        }

        const response = await this.request(
            {
                path: `/api/v2/Templates`,
                method: 'POST',
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters['body'] as any,
            },
            initOverrides,
        );

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * If SubmodelTemplatesApiUrl is configured, the endpoint returns Status403Forbidden instructing clients to use the remote templates API instead. Otherwise, it logs the payload\'s id and forwards the body to AddNewSubmodelInDefaultTemplateAasAsync.
     * Creates a new template in the templates AAS when the local endpoint is enabled.
     */
    async templatesCreateTemplate(
        requestParameters: TemplatesCreateTemplateRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<string> {
        const response = await this.templatesCreateTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all submodel templates from the templates AAS.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    async templatesGetAllTemplatesRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters['X-API-KEY'] = await this.configuration.apiKey('X-API-KEY'); // ApiKey authentication
        }

        const response = await this.request(
            {
                path: `/api/v2/Templates`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Returns all submodel templates from the templates AAS.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    async templatesGetAllTemplates(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.templatesGetAllTemplatesRaw(initOverrides);
    }
}
