export enum SubmodelElementSemanticId {
    Address = '0173-1#02-AAQ832#005',
    NameplateAddressV3 = 'https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/AddressInformation',
    MarkingsV1 = 'https://admin-shell.io/zvei/nameplate/1/0/Nameplate/Markings',
    MarkingsV2 = 'https://admin-shell.io/zvei/nameplate/2/0/Nameplate/Markings',
    MarkingsV3 = 'https://admin-shell.io/zvei/nameplate/3/0/Nameplate/Markings',
    MarkingsIrdiV1 = '0173-1#01-AGZ673#001',
    MarkingsIrdiV3 = '0112/2///61360_7#AAS006#001',
    ContactInformation = 'https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/ContactInformation',
    Document = 'https://admin-shell.io/vdi/2770/1/0/Document',
    DocumentIrdi = '0173-1#02-ABI500#001/0173-1#01-AHF579#001',
    TimeSeriesSegments = 'https://admin-shell.io/idta/TimeSeries/Segments/1/1',
    TimeSeriesLinkedSegment = 'https://admin-shell.io/idta/TimeSeries/Segments/LinkedSegment/1/1',
    TimeSeriesInternalSegment = 'https://admin-shell.io/idta/TimeSeries/Segments/InternalSegment/1/1',
    TimeSeriesSegmentName = 'https://admin-shell.io/idta/TimeSeries/Segment/Name/1/1',
    TimeSeriesRecords = 'https://admin-shell.io/idta/TimeSeries/Records/1/1',
    TimeSeriesSegmentDescription = 'https://admin-shell.io/idta/TimeSeries/Segment/Description/1/1',
    TimeSeriesLinkedSegmentEndpoint = 'https://admin-shell.io/idta/TimeSeries/Endpoint/1/1',
    TimeSeriesLinkedSegmentQuery = 'https://admin-shell.io/idta/TimeSeries/Query/1/1',
    EntryNode = 'https://admin-shell.io/idta/HierarchicalStructures/EntryNode/1/0',
    BulkCount = 'https://admin-shell.io/idta/HierarchicalStructures/BulkCount/1/0',
    ArcheType = 'https://admin-shell.io/idta/HierarchicalStructures/ArcheType/1/0'
}
