/* tslint:disable */
/* eslint-disable */
/**
 * DotAAS Part 2 | HTTP/REST | Entire API Collection
 * All APIs of the Specification of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub) in one collection. Please not that this API is not intended to generate productive code but only for overview purposes.   Publisher: Industrial Digital Twin Association (IDTA) 2023\"
 *
 * The version of the OpenAPI document: V3.0.4
 * Contact: info@idtwin.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { Result, ServiceDescription } from '../models/index';

/**
 * DescriptionAPIApi - interface
 *
 * @export
 * @interface DescriptionAPIApiInterface
 */
export interface DescriptionAPIApiInterface {
    /**
     *
     * @summary Returns the self-describing information of a network resource (ServiceDescription)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DescriptionAPIApiInterface
     */
    getDescriptionRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ServiceDescription>>;

    /**
     * Returns the self-describing information of a network resource (ServiceDescription)
     */
    getDescription(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceDescription>;
}

/**
 *
 */
export class DescriptionAPIApi extends runtime.BaseAPI implements DescriptionAPIApiInterface {
    /**
     * Returns the self-describing information of a network resource (ServiceDescription)
     */
    async getDescriptionRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<ServiceDescription>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/description`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the self-describing information of a network resource (ServiceDescription)
     */
    async getDescription(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceDescription> {
        const response = await this.getDescriptionRaw(initOverrides);
        return await response.value();
    }
}
