/* tslint:disable */
/* eslint-disable */
/**
 * DotAAS Part 2 | HTTP/REST | Entire API Collection
 * All APIs of the Specification of the [Specification of the Asset Administration Shell: Part 2](http://industrialdigitaltwin.org/en/content-hub) in one collection. Please not that this API is not intended to generate productive code but only for overview purposes.   Publisher: Industrial Digital Twin Association (IDTA) 2023\"
 *
 * The version of the OpenAPI document: V3.0.4
 * Contact: info@idtwin.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { Environment, Result } from '../models/index';

export interface GenerateSerializationByIdsRequest {
    aasIds?: Array<string>;
    submodelIds?: Array<string>;
    includeConceptDescriptions?: boolean;
}

/**
 * SerializationAPIApi - interface
 *
 * @export
 * @interface SerializationAPIApiInterface
 */
export interface SerializationAPIApiInterface {
    /**
     *
     * @summary Returns an appropriate serialization based on the specified format (see SerializationFormat)
     * @param {Array<string>} [aasIds] The Asset Administration Shells\&#39; unique ids (UTF8-BASE64-URL-encoded)
     * @param {Array<string>} [submodelIds] The Submodels\&#39; unique ids (UTF8-BASE64-URL-encoded)
     * @param {boolean} [includeConceptDescriptions] Include Concept Descriptions?
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SerializationAPIApiInterface
     */
    generateSerializationByIdsRaw(
        requestParameters: GenerateSerializationByIdsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Blob>>;

    /**
     * Returns an appropriate serialization based on the specified format (see SerializationFormat)
     */
    generateSerializationByIds(
        requestParameters: GenerateSerializationByIdsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Blob>;
}

/**
 *
 */
export class SerializationAPIApi extends runtime.BaseAPI implements SerializationAPIApiInterface {
    /**
     * Returns an appropriate serialization based on the specified format (see SerializationFormat)
     */
    async generateSerializationByIdsRaw(
        requestParameters: GenerateSerializationByIdsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<Blob>> {
        const queryParameters: any = {};

        if (requestParameters['aasIds'] != null) {
            queryParameters['aasIds'] = requestParameters['aasIds'];
        }

        if (requestParameters['submodelIds'] != null) {
            queryParameters['submodelIds'] = requestParameters['submodelIds'];
        }

        if (requestParameters['includeConceptDescriptions'] != null) {
            queryParameters['includeConceptDescriptions'] = requestParameters['includeConceptDescriptions'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/serialization`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Returns an appropriate serialization based on the specified format (see SerializationFormat)
     */
    async generateSerializationByIds(
        requestParameters: GenerateSerializationByIdsRequest = {},
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<Blob> {
        const response = await this.generateSerializationByIdsRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
