# Docker build template for multi-platform builds
.docker-build-template:
  image: docker:26.1.2
  services:
    - docker:26.1.2-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker info
    - apk add --no-cache git
    - docker buildx create --use --name mybuilder --driver docker-container