# Node.js setup template for jobs that need Node.js environment
.node-setup:
  image: node:22
  before_script:
    - yarn install --frozen-lockfile
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      - .yarn/cache/