name: CI

on:
  workflow_call:
  pull_request:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    name: e2e test matrix
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        # add more containers to run more tests in parallel
        containers: [1, 2, 3, 4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build test image
        run: docker compose -f compose.yml -f docker-compose/compose.test.yml --profile tests build cypress-test

      - name: Pull images
        run: docker compose -f compose.yml -f docker-compose/compose.test.yml --profile tests pull

      # Remove old image to avoid conflicts, before sometimes the old image wasn't loaded
      # If this step fails please check docker-compose/compose.test.yml if tag is still correct
      - name: Remove Docker image mnestix/mnestix-browser:latest, to avoid conflicts
        run: docker rmi mnestix/mnestix-browser:latest

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: '.'
          target: production
          push: false
          tags: mnestix/mnestix-browser:latest
          load: true

      - name: Run e2e tests
        # 18-minute timeout to speed up failing tests that are retried too long.
        # If the timeout is reached under normal test conditions, consider increasing
        # the number of containers to run more tests in parallel.
        timeout-minutes: 18
        run: |
          docker compose -f compose.yml -f docker-compose/compose.test.yml --profile tests up -d &&
          docker compose -f compose.yml -f docker-compose/compose.test.yml attach cypress-test
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
          TEST_ADMIN_USER_PASSWORD: ${{ secrets.TEST_ADMIN_USER_PASSWORD }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

      - name: E2E test collect artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts-${{ matrix.containers }}
          path: cypress-artifacts/

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: npx jest

  lint:
    name: Lint and Typecheck
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Typescript check
        run: yarn typecheck
      - name: Typescript e2e check
        run: yarn typecheck:e2e
      - name: Linting check
        run: yarn lint

  # Target for PR Merge Check
  ci-success:
    name: Successful build and tests
    runs-on: ubuntu-latest
    needs: ['lint', 'unit-test', 'e2e-tests']
    permissions:
      contents: read
    steps:
      - name: Success
        run: echo "Success"
