/* tslint:disable */
/* eslint-disable */
/**
 * Mnestix AAS Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: info@xitaso.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ProblemDetails } from '../models/index';

export interface TemplatesGetAllTemplatesRequest {
    xApiVersion: string | null;
}

/**
 * TemplatesApi - interface
 *
 * @export
 * @interface TemplatesApiInterface
 */
export interface TemplatesApiInterface {
    /**
     *
     * @summary ONLY FOR INTERNAL USAGE. BearerToken needed. Returns all submodel templates from the templates AAS.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     * @param {string} xApiVersion
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TemplatesApiInterface
     */
    templatesGetAllTemplatesRaw(
        requestParameters: TemplatesGetAllTemplatesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>>;

    /**
     * ONLY FOR INTERNAL USAGE. BearerToken needed. Returns all submodel templates from the templates AAS.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    templatesGetAllTemplates(
        requestParameters: TemplatesGetAllTemplatesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void>;
}

/**
 *
 */
export class TemplatesApi extends runtime.BaseAPI implements TemplatesApiInterface {
    /**
     * ONLY FOR INTERNAL USAGE. BearerToken needed. Returns all submodel templates from the templates AAS.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    async templatesGetAllTemplatesRaw(
        requestParameters: TemplatesGetAllTemplatesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['xApiVersion'] == null) {
            throw new runtime.RequiredError(
                'xApiVersion',
                'Required parameter "xApiVersion" was null or undefined when calling templatesGetAllTemplates().',
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xApiVersion'] != null) {
            headerParameters['x-api-version'] = String(requestParameters['xApiVersion']);
        }

        const response = await this.request(
            {
                path: `/api/Templates`,
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ONLY FOR INTERNAL USAGE. BearerToken needed. Returns all submodel templates from the templates AAS.  This endpoint uses the template transformer to ensure the returned submodels are standard conform.
     */
    async templatesGetAllTemplates(
        requestParameters: TemplatesGetAllTemplatesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<void> {
        await this.templatesGetAllTemplatesRaw(requestParameters, initOverrides);
    }
}
